### ISSUE TITLE
Ignore variable names in DBus interfaces

### ISSUE THREAD

**Issue by danrabbit** [vala-lang/vala-lint#120]
So maybe instead of #118 what we really want is to ignore variable naming convention checks in DBus interfaces since we don't have control over someone else's API and it seems like it's pretty common for naming conventions to break the linter.

Example here: https://github.com/elementary/wingpanel-indicator-power/pull/121/files

**Comment by tintou** [comment]
Vala transforms `foo_bar_baz` into `FooBarBaz` as recommended by D-Bus so it's safe to lint this

**Comment by tintou** [comment]
Exceptions can be handled using `[DBus (name = "CRAZYDBusMethodNaMiNG")]`

**Comment by danrabbit** [comment]
Ah okay so then I'll close this
