### ISSUE TITLE
May scan inappropriate files

### ISSUE THREAD

**Issue by jeremypw** [vala-lang/vala-lint#63]
If invoked using e.g. a meson.build file or such a non-vala file is included as part of a wild card 

e.g. io.elementary.vala-lint ..../src/*  then this file is scanned anyway.  This is not necessarily a problem for some non-vala files (e.g diffs) and for some tests but it is possible to crash the vala parser this way.

**Comment by pantor** [comment]
Currently, we have two ways to tell Vala-lint which files to lint, either by `vala-lint -d src` using the command line directory flag or using globs `vala-lint src/*`. The directory flag automatically lints only vala-related files.
I think we should integrate the directory option without explicit flag: If the argument is a directory, we lint only vala-related files recursively, if the argument is a glob, we keep linting every match. Then, `io.elementary.vala-lint ..../src/*` should be replaced by `io.elementary.vala-lint ..../src/`. I hope that would fix the issue.

**Comment by jeremypw** [comment]
Is there a use-case for linting non-vala files?

**Comment by pantor** [comment]
I don’t know, maybe for diffs (as you mentioned before) or some kind of template files?

**Comment by jeremypw** [comment]
I think vala-lint would only be expected to lint vala language files (maybe including vapi files?) - any more could be regarded as mission creep.  At least some different code would have to be written to lint other file types (meson-lint etc) with different syntax reliably.
