### ISSUE TITLE
Option for basic and pedantic checks

### ISSUE THREAD

**Issue by jeremypw** [vala-lang/vala-lint#64]
I think it would be good in future to have the ability to be able to regard certain checks as "mandatory" for elementary code and others as "recommended" as the conventions used in different projects vary somewhat.  This would avoid more serious problems being swamped by minor problems.

Running vala-lint without an option would run only the mandatory checks whereas running with a --pedantic flag would use all tests.

**Comment by pantor** [comment]
Fixed by #103 and #89.
